[package]
name = "ButterflyAPI"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = {version = "0.8.4", features = ["macros"]}
bb8 = "0.9.1"
constcat = "0.6.1"
diesel = {version = "2.2.12", features = ["postgres", "uuid"] }
diesel-async = { version = "0.7.0", features = ["postgres", "bb8", "pool"] }
dotenvy = "0.15.7"
hex = "0.4.3"
rand_core = "0.9.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["trace"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4", "serde"
]
