apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: butterfly-api
  namespace: butterfly-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - butterflyvr.net
        - www.butterflyvr.net
        - api.butterflyvr.net
      secretName: butterfly-api-tls
  rules:
    - host: butterflyvr.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: butterfly-api
                port:
                  number: 80
    - host: www.butterflyvr.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: butterfly-api
                port:
                  number: 80
    - host: api.butterflyvr.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: butterfly-api
                port:
                  number: 80
